# backend/ml_model.py
import logging
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from backend.risk_engine import RiskCalculator
import warnings

# Suppress sklearn warnings for cleaner production logs
warnings.filterwarnings('ignore')

# Initialize logging
logger = logging.getLogger("MLEngine")

class RiskPredictor:
    def __init__(self, ticker: str):
        self.ticker = ticker
        
        try:
            engine = RiskCalculator(ticker)
            self.df = engine.df
        except Exception as e:
            logger.error(f"Failed to initialize RiskCalculator for {ticker}: {e}")
            self.df = pd.DataFrame()
            
        self.model = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')
        # Extended feature set for better predictive accuracy
        self.feature_names = [
            'SMA_10', 'SMA_30', 'Rolling_Vol_10', 'Momentum_5', 
            'RSI_14', 'MACD', 'Volume_Change'
        ]

    def _engineer_features(self) -> pd.DataFrame:
        """Creates advanced technical indicators for the ML model."""
        if self.df.empty:
            logger.warning(f"No data available to engineer features for {self.ticker}.")
            return None

        df = self.df.copy()
        
        try:
            # 1. Moving Averages & Volatility
            df['SMA_10'] = df['close_price'].rolling(window=10).mean()
            df['SMA_30'] = df['close_price'].rolling(window=30).mean()
            df['Rolling_Vol_10'] = df['daily_return'].rolling(window=10).std()
            df['Momentum_5'] = df['close_price'].pct_change(periods=5)

            # 2. RSI (Relative Strength Index)
            delta = df['close_price'].diff()
            gain = (delta.where(delta > 0, 0)).ewm(alpha=1/14, adjust=False).mean()
            loss = (-delta.where(delta < 0, 0)).ewm(alpha=1/14, adjust=False).mean()
            rs = gain / loss
            df['RSI_14'] = 100 - (100 / (1 + rs))

            # 3. MACD (Moving Average Convergence Divergence)
            ema_12 = df['close_price'].ewm(span=12, adjust=False).mean()
            ema_26 = df['close_price'].ewm(span=26, adjust=False).mean()
            df['MACD'] = ema_12 - ema_26

            # 4. Volume Momentum
            df['Volume_Change'] = df['volume'].pct_change()

            # 5. Target Variable (Drop of > 1.5%)
            df['Target_High_Risk'] = (df['daily_return'].shift(-1) < -0.015).astype(int)

            # --- THE INFINITY FIX ---
            # Replace any 'Infinity' generated by division-by-zero with 'NaN' (blank)
            df.replace([np.inf, -np.inf], np.nan, inplace=True)
            # Drop any row that contains a 'NaN' to ensure the AI gets perfectly clean data
            df.dropna(inplace=True)

            return df
        except Exception as e:
            logger.error(f"Error engineering features for {self.ticker}: {e}")
            return None

    def train_and_predict(self) -> dict:
        """Trains the Random Forest and predicts tomorrow's risk with detailed Explainability."""
        logger.info(f"Initiating ML Training & Prediction for {self.ticker}...")
        
        df_ml = self._engineer_features()
        if df_ml is None or df_ml.empty:
            logger.error(f"Insufficient data to train ML model for {self.ticker}.")
            return {"error": f"Insufficient historical data to predict risk for {self.ticker}."}

        try:
            # 1. Isolate 'Today' (Ensure we don't have NaN in target features)
            train_data = df_ml.iloc[:-1].dropna(subset=self.feature_names + ['Target_High_Risk'])
            
            # If after dropping NaNs we don't have enough rows to train, abort.
            if len(train_data) < 50:
                 return {"error": f"Not enough valid training data for {self.ticker} after feature engineering."}
                 
            today_data = df_ml.iloc[-1:] 
            
            X_train = train_data[self.feature_names]
            y_train = train_data['Target_High_Risk']

            # 2. Train Model
            self.model.fit(X_train, y_train)

            # 3. Predict Today
            X_today = today_data[self.feature_names]
            
            # Handle edge case where the very last row has NaNs
            if X_today.isnull().values.any():
                X_today = X_today.fillna(0) # Basic imputation to prevent crashing
                
            risk_probability = self.model.predict_proba(X_today)[0][1]
            is_high_risk = bool(self.model.predict(X_today)[0])

            # 4. EXPLAINABLE AI (Simulated SHAP Breakdown for UI)
            importances = self.model.feature_importances_
            
            shap_breakdown = []
            for name, importance in zip(self.feature_names, importances):
                # Scale relative to final probability for UI comprehension
                scaled_impact = float(importance * risk_probability * 100)
                current_val = float(X_today[name].iloc[0])
                
                shap_breakdown.append({
                    "feature": name,
                    "current_value": round(current_val, 4),
                    "impact_percentage": round(scaled_impact, 2)
                })
                
            # Sort so the highest impact is at the top
            shap_breakdown.sort(key=lambda x: x['impact_percentage'], reverse=True)

            logger.info(f"Prediction complete for {self.ticker}. Probability: {risk_probability:.2%}")

            return {
                "ticker": self.ticker,
                "risk_probability": round(risk_probability * 100, 2),
                "is_high_risk_tomorrow": is_high_risk,
                "top_risk_driver": shap_breakdown[0]['feature'] if shap_breakdown else "Unknown",
                "shap_breakdown": shap_breakdown 
            }
            
        except Exception as e:
            logger.error(f"Critical failure during ML inference for {self.ticker}: {e}")
            return {"error": "Internal AI processing error."}